apiVersion: v1
kind: Service
metadata:
  name: football-league-service
  labels:
    name: football-league-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: football-league
  type: LoadBalancer
